In [5]:
from dataloader import load_data
from sklearn.cluster import KMeans
import numpy as np

In [2]:
data = load_data('img/Thinking-of-getting-a-cat.png')

# creating a kmeans model with 2 clusters

In [6]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(data)

kmeans.cluster_centers_

array([[ 81.30954764,  58.07288162,  37.49393961],
       [154.44765538, 153.55741972, 154.83102178]])

In [12]:
kmeans.labels_

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
kmeans.predict([[255, 255,35], [12, 3,4]])

array([1, 0])

In [ ]:
# 